name: dagre_d3
description: A D3-based renderer for Dagre
dependencies:
  dagre:
    path: ../dagre
  graphlib:
    path: ../graphlib
  graphlib_dot:
    path: ../graphlib_dot
  unittest: any
dev_dependencies:
  d3:
    path: ../d3
