name: dagre_d3
description: A D3-based renderer for Dagre
dependencies:
  charted: any
  dagre:
    path: ../dagre
  graphlib:
    path: ../graphlib
  graphlib_dot:
    path: ../graphlib_dot
  unittest: any
